a few clean-up tweaks to make it easier to run on different systems

diff --git a/src-Linux/runLinux/run b/src-Linux/runLinux/run
--- a/src-Linux/runLinux/run
+++ b/src-Linux/runLinux/run
@@ -1,55 +1,89 @@
 #!/bin/bash
 
-# Initialise
-#=====================================================
+# exit on errors
+set -e
 
-solstice_dir='/home/yewang/Solstice-0.8.1-GNU-Linux64'
+#-------------------------------------------------------------------------------
+# initialise all needed file locations
 
-#======================================================
-#
-#
-#
-python set_case.py
-#
-case_dir="`cat $solstice_dir/casedir.input`"
-azimuth="`cat $case_dir/azimuth.input`"
-elevation="`cat $case_dir/elevation.input`"
-num_rays="`cat $case_dir/rays.input`"
-rho_mirror="`cat $case_dir/mirror.input`"
+# location where the Solstice binary tarball was unpacked...
+solstice_dir=$HOME/01OKDND/solstice/Solstice-0.8.2-GNU-Linux64
 
+# location of solstice post-processing C codes, eg solppraw.c
+#solpp_dir=$solstice_dir/src-Linux/ppLinux
+solpp_dir=$HOME/01OKDND/solstice/Solstice-PP-Sources-0.3.1
+
+
+#-------------------------------------------------------------------------------
+# configure the environment to run Solstice
 solstice_pack=$solstice_dir'/etc/solstice.profile'
 source $solstice_pack
+
+# export the SOLSTICE_PATH so that subsidiary scripts can find solstice
+export SOLSTICE_PATH=$solstice_path
+
+#-------------------------------------------------------------------------------
+# quick-and-dirty compile of the post-processing code if needed
+
+if [ ! -f "$solpp_dir/solppraw" ]; then
+	gcc $solpp_dir/solmaps.c -o $solpp_dir/solmaps
+	gcc $solpp_dir/solpp.c -o $solpp_dir/solpp
+	gcc $solpp_dir/solppraw.c -o $solpp_dir/solppraw
+	gcc $solpp_dir/solpaths.c -o $solpp_dir/solpath
+fi
+
+#-------------------------------------------------------------------------------
+# set up some solstice input files
+
+export CASEFOLDER="1-example/results"
+python set_case.py
+
+azimuth="`cat $CASEFOLDER/azimuth.input`"
+elevation="`cat $CASEFOLDER/elevation.input`"
+num_rays="`cat $CASEFOLDER/rays.input`"
+rho_mirror="`cat $CASEFOLDER/mirror.input`"
+
 # run solstice
 #
-solstice -D$azimuth,$elevation -v -n $num_rays -R $case_dir/input-rcv.yaml -fo $case_dir/simul $case_dir/input.yaml
+echo "Running solstice..."
+
+solstice -D$azimuth,$elevation -v -n $num_rays -R $CASEFOLDER/input-rcv.yaml -fo $CASEFOLDER/simul $CASEFOLDER/input.yaml
 #
 # preparing post processing
-solstice -D$azimuth,$elevation -g format=obj:split=geometry -fo $case_dir/geom $case_dir/input.yaml
-solstice -D$azimuth,$elevation -q -n 100 -R $case_dir/input-rcv.yaml -p default $case_dir/input.yaml > $case_dir/solpaths
-#
+echo "Preparing post-processing..."
+
+solstice -D$azimuth,$elevation -g format=obj:split=geometry -fo $CASEFOLDER/geom $CASEFOLDER/input.yaml
+solstice -D$azimuth,$elevation -q -n 100 -R $CASEFOLDER/input-rcv.yaml -p default $CASEFOLDER/input.yaml > $CASEFOLDER/solpaths
+
+#-------------------------------------------------------------------------------
 # postprocessing in C (provided by Cyril Caliot)
+
+echo "Post-processing..."
+
+pushd $CASEFOLDER > /dev/null
 #Read "simul" results and produce a text file with the raw results
-gcc $solstice_dir/src-Linux/ppLinux/solppraw.c -o $solstice_dir/src-Linux/ppLinux/solppraw
-$solstice_dir/src-Linux/ppLinux/solppraw $case_dir/simul
+$solpp_dir/solppraw simul
+
 #Read "simul" results and produce receiver files (.vtk) of incoming and/or absorbed solar flux per-primitive
-gcc $solstice_dir/src-Linux/ppLinux/solmaps.c -o $solstice_dir/src-Linux/ppLinux/solmaps
-$solstice_dir/src-Linux/ppLinux/solmaps $case_dir/simul
+$solpp_dir/solmaps simul
 
 #Read "geom" and "simul" file results and produce primaries and receivers files (.vtk), and .obj geometry files
-gcc $solstice_dir/src-Linux/ppLinux/solpp.c -o $solstice_dir/src-Linux/ppLinux/solpp
-$solstice_dir/src-Linux/ppLinux/solpp $case_dir/geom $case_dir/simul
+$solpp_dir/solpp geom simul
 
 #Read "solpaths" file and produce readable file (.vtk) by paraview to visualize the ray paths
-gcc $solstice_dir/src-Linux/ppLinux/solpaths.c -o $solstice_dir/src-Linux/ppLinux/solpath
-$solstice_dir/src-Linux/ppLinux/solpath $case_dir/solpaths
+$solpp_dir/solpath solpaths
 
-mv *vtk $case_dir
-mv *obj $case_dir
-mv *txt $case_dir
-rm $solstice_dir/*.input
-rm $case_dir/*input
+popd > /dev/null
 
+#-------------------------------------------------------------------------------
+# places files in $CASEFOLDER (FIXME: put them there in the first place!)
+#mv *vtk $CASEFOLDER
+#mv *obj $CASEFOLDER
+#mv *txt $CASEFOLDER
 
-rawfile=$case_dir'/simul'
-python $solstice_dir/src-Linux/srcPy/get_raw.py $rawfile $case_dir $rho_mirror
+# FIXME why do we remove these input files??
+#rm $CASEFOLDER/*input
+
+rawfile=$CASEFOLDER'/simul'
+python ../srcPy/get_raw.py $rawfile $CASEFOLDER $rho_mirror
 
